pipeline:
  identifier: Build_NodeGoat_1684346648623
  name: Build NodeGoat
  orgIdentifier: default
  projectIdentifier: VishNodeGoat
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1684246355606
        repoName: Vishnu-Harness/NodeGoat
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
